### ISSUE TITLE
more of a question

### ISSUE THREAD

**Issue by davecramer** [duanebester/clunk#1]
Curious why not just use R2DBC https://r2dbc.io/ ?

**Comment by duanebester** [comment]
@davecramer great question! Mostly for learning Clojure! However, i'm only interested in Postgres and then keeping this to minimal dependencies, as well as pure cljc, it adds support for Node, and [Babashka](https://github.com/babashka/babashka)

**Comment by davecramer** [comment]
cool. So I am one of the maintainers for the PostgreSQL JDBC driver. Love to see anything PostgreSQL. If you have questions about the protocol, don't hesitate. In the meantime I'll be following this ! Cheers

**Comment by duanebester** [comment]
Excellent, thanks @davecramer!
